// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, public_member_api_docs
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAigmSkwWIpwK1QPRgsFsEBqL9n89ajrPo',
    appId: '1:650017325533:web:9164abb5346405e56c7634',
    messagingSenderId: '650017325533',
    projectId: 'we-do-flutter',
    authDomain: 'we-do-flutter.firebaseapp.com',
    databaseURL:
        'https://we-do-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'we-do-flutter.appspot.com',
    measurementId: 'G-NP3DXJZVJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZWTLfyvHP23CF5xJ1dVXbF5AXyiJVXI4',
    appId: '1:650017325533:android:95dc2f75c6628a5d6c7634',
    messagingSenderId: '650017325533',
    projectId: 'we-do-flutter',
    databaseURL:
        'https://we-do-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'we-do-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSW5wYNaG1pp88OXm2yDrYjIZNsEuZ2U0',
    appId: '1:650017325533:ios:a4617ed5afee75126c7634',
    messagingSenderId: '650017325533',
    projectId: 'we-do-flutter',
    databaseURL:
        'https://we-do-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'we-do-flutter.appspot.com',
    iosBundleId: 'com.adilhanney.weDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSW5wYNaG1pp88OXm2yDrYjIZNsEuZ2U0',
    appId: '1:650017325533:ios:eb61734dd67ad9036c7634',
    messagingSenderId: '650017325533',
    projectId: 'we-do-flutter',
    databaseURL:
        'https://we-do-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'we-do-flutter.appspot.com',
    iosBundleId: 'com.adilhanney.weDo.RunnerTests',
  );
}
